import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/lib/lenis";
import { LenisOptions } from "lenis";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lenisOption: LenisOptions = {
    duration: 2,
  };

  return (
    <html lang="en">
      <ReactLenis root options={lenisOption}>
        <body
          className={`${inter.variable} ${montserrat.variable} antialiased w-full min-h-screen font-montserrat`}
        >
          {children}
        </body>
      </ReactLenis>
    </html>
  );
}
